blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blogger/<int:pk>', views.BlogListbyAuthorView.as_view(), name='blogs-by-author'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='blog_comment'),
    url(r'^blog/create/$', views.BlogCreate.as_view(), name='blog_create'),
    url(r'^blog/(?P<pk>\d+)/update/$', views.BlogUpdate.as_view(), name='blog_update'),
    url(r'^blog/(?P<pk>\d+)/delete/$', views.BlogDelete.as_view(), name='blog_delete'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # Redirect
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User  # Blog author or commenter


class BlogAuthor(models.Model):
    """
    Model representing a blogger.
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, default="Enter your bio details here.")

    class Meta:
        ordering = ["user", "bio"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog-author instance.
        """
        return reverse('blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.user.username


class Blog(models.Model):
    """
    Model representing a blog post.
    """
    name = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because Blog can only have one User, but user can have multiple blog posts.
    description = models.TextField(max_length=2000, default="Enter you blog text here.")
    post_date = models.DateField(default=date.today)

    class Meta:
        ordering = ["-post_date"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular blog instance.
        """
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class BlogComment(models.Model):
    """
    Model representing a comment against a blog post.
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because BlogComment can only have one author/User, but users can have multiple comments
    post_date = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        String for representing the Model object.
        """
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Blog, BlogAuthor, BlogComment
from django.contrib.auth.models import User  # Blog author or commenter
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic import DetailView


def index(request):
    """
    View function for home page of site.
    """
    num_blogs = Blog.objects.all().count()
    num_authors = BlogAuthor.objects.all().count()
    # Render the HTML template index.html
    return render(request, 'index.html',
                  context={'num_blogs': num_blogs, 'num_authors': num_authors,},
                  )



class BlogListView(generic.ListView):
    """
    Generic class-based view for a list of all blogs.
    """
    model = Blog
    paginate_by = 5


class BlogListbyAuthorView(generic.ListView):
    """
    Generic class-based view for a list of blogs posted by a particular BlogAuthor.
    """
    model = Blog
    paginate_by = 5
    template_name = 'blog/blog_list_by_author.html'

    def get_queryset(self):
        """
        Return list of Blog objects created by BlogAuthor (author id specified in URL)
        """
        id = self.kwargs['pk']
        target_author = get_object_or_404(User, pk=id)
        return Blog.objects.filter(author=target_author)

    def get_context_data(self, **kwargs):
        """
        Add BlogAuthor to context so they can be displayed in the template
        """
        # Call the base implementation first to get a context
        context = super(BlogListbyAuthorView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogger'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context


class BlogDetailView(generic.DetailView):
    """
    Generic class-based detail view for a blog.
    """
    model = Blog


class BloggerListView(generic.ListView):
    """
    Generic class-based view for a list of bloggers.
    """
    model = User
    paginate_by = 5


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login.
    """
    model = BlogComment
    fields = ['description', ]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        # Add logged-in user as author of comment
        form.instance.author = self.request.user
        # Associate comment with blog based on passed id
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })


class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['name','description',]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(BlogCreate, self).form_valid(form)


class BlogUpdate(UpdateView):
    model = Blog
    fields = '__all__'


class BlogDelete(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs')

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Django DIY Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'blogs' %}">All blogs</a></li>
    <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
  </ul>
  
  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
	 <li><a href="{% url 'blog_create' %}">Create a new blog</a></li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
		or<br>
     <li><a href="/accounts/register/">Register</a></li><br>	
   {% endif %} 
  </ul>
 
  {% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}
  
  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  
  </div>
</div>

</div>
</body>
</html>

blog/templates/base_registration.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}style.css" />
    <title>{% block title %}User test{% endblock %}</title>
</head>

<body>
    <div id="header">
    {% block header %}
    <a href="{% url 'index' %}">{% trans "Home" %}</a> | 
    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }} 
        (<a href="{% url 'logout' %}">{% trans "Log out" %}</a> | 
        <a href="{% url 'password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'login' %}">{% trans "Log in" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
</body>

</html>

blog/templates/blog/blog_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blog</h1>

<p>Are you sure you want to delete the blog: {{ blog}}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<a href="{% url 'blog_update' blog.pk %}">(Edit blog)</a>  <a href="{% url 'blog_delete' blog.pk %}">(Delete blog)</a>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog_comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All blogs</h1>

    {% if blog_list %}
    <ul>

      {% for blog in blog_list %}
	  {% if user.is_staff %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}}) — <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a> -- <a href="{% url 'blog_update' blog.pk %}">(Edit blog)</a> -- <a href="{% url 'blog_delete' blog.pk %}">(Delete blog)</a>
      </li>
	  {% else %}
	  <li>
	  <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}}) — <a href="{% url 'blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
	  </li>
      {% endif %}
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no blogs.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blog_list_by_author.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{blogger}}</h1>
    
    <h3>Bio</h3>
    
    <p>{{blogger.bio}}</p>
    
    

    {% if blog_list %}
    <h3>Blogs list</h3>
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>This blogger hasn't posted anything yet.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blogauthor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All bloggers</h1>

    {% if blogauthor_list %}
    <ul>

      {% for author in blogauthor_list %}
      <li>
        <a href="{% url 'blogs-by-author' author.pk %}">{{ author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no bloggers yet.</p>
    {% endif %}       
{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}


<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blog/templates/django_registration/registration_complete.html
{% extends "base_registration.html" %}
{% load i18n %}
{% csrf_token %}
{% block content %}
<p>{% trans "You are now registered. Activation email sent." %}</p>
{% endblock %}

blog/templates/django_registration/registration_form.html
{% extends "base_registration.html" %}
{% load i18n %}

{% block content %}
<form method="post" action=".">
  {% csrf_token %}
  {{ form.as_p }}

  <input type="submit" value="{% trans 'Submit' %}" />
</form>
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>DIY Blog Home</h1>

<p>Welcome to <em>DIY Blog</em>, a very basic Django blogging website developed as an <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog">assessment task</a> for the Django learning module on the Mozilla Developer Network.</p>
<p>Site has the following record counts:</p>
  <ul>
    <li><strong>Blogs:</strong> {{ num_blogs }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}